FROM rust:1.75 as builder
WORKDIR /app

ADD . .

RUN cargo build --release --bin evm-block-extractor

FROM debian:bookworm-slim AS runtime

# GCP BigQuery Environment Variables
ARG DATASET
ARG PROJECT_ID
ARG GCP_BLOCK_EXTRACTOR_SA_KEY

# Set environment variables
ENV DATASET=$DATASET \
    PROJECT_ID=$PROJECT_ID \
    GCP_BLOCK_EXTRACTOR_SA_KEY=$GCP_BLOCK_EXTRACTOR_SA_KEY

WORKDIR /app
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends ca-certificates \
    && update-ca-certificates \
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/evm-block-extractor /app/evm-block-extractor

EXPOSE 8080

ENTRYPOINT ["./evm-block-extractor"]

